### ISSUE TITLE
Requirements.tx desatualizado

### ISSUE THREAD

**Issue by JonhatanHaisi** [IgdaliasCabamba/icode#2]
Aparentemente o requirements.txt está desatualizado. Eu criei o venv (python -m venv smartenv), instalei as deendencias (pip install -r requirements.txt) e estpa dando erro para iniciar o projeto.
Fui tentando instalar manualmente, mas aparentemente está faltando bastante coisa

`D:\projects\icode (main -> origin)
(smartenv) λ python icode\app.py
Traceback (most recent call last):
  File "D:\projects\icode\icode\app.py", line 46, in <module>
    main = importlib.import_module("main", "src")
  File "C:\Users\JONAT\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\projects\icode\icode\src\main.py", line 1, in <module>
    from core import *
  File "D:\projects\icode\icode\src\core\__init__.py", line 1, in <module>
    from .april import *
  File "D:\projects\icode\icode\src\core\april\__init__.py", line 1, in <module>
    from .aprildev import *
  File "D:\projects\icode\icode\src\core\april\aprildev.py", line 1, in <module>
    from howdoi.howdoi import howdoi
ModuleNotFoundError: No module named 'howdoi'
`

**Comment by IgdaliasCabamba** [comment]
Olá @JonhatanHaisi que bom que decidiu testar o icode e até abrir uma 'issue', não tem ideia de como isso motiva!

Infelizmente eu não uso windows e minha máquina tem apenas 4GB de ram então só uso o Windows no Virtualbox para compilar o Icode, mas eu usei o virtualenv(diferente do venv) e o programa funcionou, mesmo depois de ter usado o cx-freeze, ele funcionou sem nenhum problema com dependências!

Tente isso:

1. Solução corrigir a variável de ambiente $PATH:
[Mais detalhes aqui](https://stackoverflow.com/questions/48130371/python-venv-modulenotfounderror)

2. Solução talvez possa usar o virtualenv ao invés do venv:
`pip install virtualenv`


Mas acho que não vou poder dar suporte para o Windows agora, pois pretendo dar uma repaginada no projeto todo, ao invés de ser um editor, o Icode vai ser uma IDE com um novo visual e uma integração completa com o Python, pode ajudar com o projeto e fazer parte da comunidade por se juntar ao nosso servidor no Discord!

[Servidor do Icode](https://discord.gg/gG9rB6Xk)
